// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsO2aBNLHNhePkFL9T_0ItSg5BFE1bR8',
    appId: '1:833595179103:web:aa8dcee5ca40c5d6ec5bea',
    messagingSenderId: '833595179103',
    projectId: 'blog-sys-c38a9',
    authDomain: 'blog-sys-c38a9.firebaseapp.com',
    storageBucket: 'blog-sys-c38a9.firebasestorage.app',
    measurementId: 'G-QJH4SM61LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfB-UPWWW8hhym8Z5-rxbZwmq1tStHk2E',
    appId: '1:833595179103:android:1e90e12dc40dd25dec5bea',
    messagingSenderId: '833595179103',
    projectId: 'blog-sys-c38a9',
    storageBucket: 'blog-sys-c38a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXs2zHgf1H3M-f0Hx8oFA27tthbSaIjRY',
    appId: '1:833595179103:ios:5d6b34fbf26b7487ec5bea',
    messagingSenderId: '833595179103',
    projectId: 'blog-sys-c38a9',
    storageBucket: 'blog-sys-c38a9.firebasestorage.app',
    iosBundleId: 'com.example.blogSys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXs2zHgf1H3M-f0Hx8oFA27tthbSaIjRY',
    appId: '1:833595179103:ios:5d6b34fbf26b7487ec5bea',
    messagingSenderId: '833595179103',
    projectId: 'blog-sys-c38a9',
    storageBucket: 'blog-sys-c38a9.firebasestorage.app',
    iosBundleId: 'com.example.blogSys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYsO2aBNLHNhePkFL9T_0ItSg5BFE1bR8',
    appId: '1:833595179103:web:a8e3aa9e463420b5ec5bea',
    messagingSenderId: '833595179103',
    projectId: 'blog-sys-c38a9',
    authDomain: 'blog-sys-c38a9.firebaseapp.com',
    storageBucket: 'blog-sys-c38a9.firebasestorage.app',
    measurementId: 'G-EM5W8J0GC9',
  );

}