// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7OunbPp-VYqGBNdUtI0YQYp7kdkyzdw',
    appId: '1:916436872709:web:688a7596fe8fb8cf59b66c',
    messagingSenderId: '916436872709',
    projectId: 'blog-system-app',
    authDomain: 'blog-system-app.firebaseapp.com',
    databaseURL: 'https://blog-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'blog-system-app.firebasestorage.app',
    measurementId: 'G-QFR83H23Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVrXFWCUlXk9qb5U5QeaWtrpgaBSVHGw',
    appId: '1:916436872709:android:d78a5918d8306b0159b66c',
    messagingSenderId: '916436872709',
    projectId: 'blog-system-app',
    databaseURL: 'https://blog-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'blog-system-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmHBjvV_419FOa2rdv_YqWttjTW23_p7w',
    appId: '1:916436872709:ios:a2ec193a3c045fd259b66c',
    messagingSenderId: '916436872709',
    projectId: 'blog-system-app',
    databaseURL: 'https://blog-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'blog-system-app.firebasestorage.app',
    iosBundleId: 'com.example.blogSystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmHBjvV_419FOa2rdv_YqWttjTW23_p7w',
    appId: '1:916436872709:ios:a2ec193a3c045fd259b66c',
    messagingSenderId: '916436872709',
    projectId: 'blog-system-app',
    databaseURL: 'https://blog-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'blog-system-app.firebasestorage.app',
    iosBundleId: 'com.example.blogSystemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7OunbPp-VYqGBNdUtI0YQYp7kdkyzdw',
    appId: '1:916436872709:web:0e97398a5caa96b859b66c',
    messagingSenderId: '916436872709',
    projectId: 'blog-system-app',
    authDomain: 'blog-system-app.firebaseapp.com',
    databaseURL: 'https://blog-system-app-default-rtdb.firebaseio.com',
    storageBucket: 'blog-system-app.firebasestorage.app',
    measurementId: 'G-ZYTWT879DB',
  );
}
